name: Global Bot Pro
on:
  schedule:
    - cron: '0 * * * *' # تشغيل كل ساعة (موفر جداً للدقائق)
  workflow_dispatch: # زر تشغيل يدوي

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install requests google-generativeai

      - name: Execute Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          NEWS_CHANNEL: ${{ secrets.NEWS_CHANNEL }}
          JOBS_CHANNEL: ${{ secrets.JOBS_CHANNEL }}
          GMY: ${{ secrets.GMY }}
        run: python script.py

      - name: Save History
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add last_news_id.txt jobs_history.txt || echo "No files"
          git commit -m "Update history" && git push || echo "No changes"
